function [settings_str] = print_ABAnnotate_input(opt)
%function [settings_str] = print_gcea_settings(gcea_opt)

% if gene/weight thresholding settings set:
if opt.GCEA.weights_quant
    weights_quant = sprintf('- Keeping annotated genes with weights exceeding the %uth quantile \n', ...
                            opt.GCEA.weights_quant * 100);
else
    weights_quant = '';
end
if opt.GCEA.weights_thresh
    weights_thresh = sprintf('- Keeping annotated genes with weights exceeding %4.2f \n', ...
                             opt.GCEA.weights_thresh);
else
    weights_thresh = '';
end
if opt.GCEA.weights_cutoff
    weights_cutoff = sprintf('- Weighting gene-category-phenotype-associations if <weightedmean> is set \n');
else
    weights_cutoff = sprintf('- Using binarized gene-category-phenotype-associations \n');
end

% make string
settings_str = [...
    sprintf('GCEA settings: \n'), ...
    sprintf('- Using phenotype data from: %s \n', ...
            opt.phenotype), ...
    sprintf('- Using atlas with %u regions: %s \n', ...
            opt.n_rois, opt.atlas), ...
    sprintf('- Using %u phenotype null maps: %s \n', ...
            opt.n_nulls, opt.phenotype_nulls), ...
    sprintf('- Using dataset: %s \n', ...
            opt.GCEA.dataset_mat), ...
    sprintf('- Including categories with between %u and %u genes \n', ...
            opt.GCEA.size_filter(1), opt.GCEA.size_filter(2)), ...
    sprintf('- Removing annotates genes that co-occur in >= %u percent of categories \n', ...
            opt.GCEA.gene_coocc_thresh * 100), ...
    weights_quant, ... 
    weights_thresh, ... 
    weights_cutoff, ...
    sprintf('- Estimating %u category null samples \n', ...
            opt.GCEA.n_category_nulls), ...
    sprintf('- Calculating gene scores based on %s correlations \n', ...
            opt.GCEA.correlation_method), ...
    sprintf('- Aggregating gene scores per category by %s \n', ...
            opt.GCEA.aggregation_method), ...
    sprintf('- Calculating p-values from %s tail at BH-corrected p < %1.4f \n\n', ...
            opt.GCEA.p_tail, opt.GCEA.p_thresh)];
          
% print
disp(settings_str);
end
     
     
    
